[build]
  command = "yarn --cwd ./frontend install --frozen-lockfile && yarn --cwd ./frontend build"
  functions = "netlify/functions"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://agendamento-de-exames-demissionais.vercel.app/api/:splat"
  status = 200
  force = true
  # preserve_query is automatically handled by Netlify
